name: Tier 1 Application Deploy

on:
  workflow_dispatch:

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ACR_ADMIN_PASSWORD: ${{ secrets.ACR_ADMIN_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          echo $ACR_ADMIN_PASSWORD | docker login docduckgooseacr.azurecr.io --username docduckgooseacr --password-stdin
        env:
          ACR_ADMIN_PASSWORD: ${{ secrets.ACR_ADMIN_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t docduckgooseacr.azurecr.io/docduckgoose-api:latest ./DocDuckGoose/sln/DocDuckGoose/DocDuckGoose.Api

      - name: Push Docker image to ACR
        run: |
          docker push docduckgooseacr.azurecr.io/docduckgoose-api:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./infrastructure/terraform/azure/tier1
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infrastructure/terraform/azure/tier1
        run: |
          terraform apply -auto-approve \
            -var="acr_admin_password=${{ env.ACR_ADMIN_PASSWORD }}" \
