name: Tier 1 - Application Deploy

on:
  workflow_dispatch: # manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        run: |
          az acr login --name docduckgooseacr

      - name: Build Docker Image
        run: |
          docker build -t docduckgooseacr.azurecr.io/docduckgoose-api:latest -f DocDuckGoose.Api/Dockerfile DocDuckGoose.Api

      - name: Push Docker Image
        run: |
          docker push docduckgooseacr.azurecr.io/docduckgoose-api:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./terraform/tier1
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform/tier1
        run: terraform apply -auto-approve -var="resource_group_name=docduckgoose-rg" -var="location=westus2" -var="acr_login_server=docduckgooseacr.azurecr.io" -var="acr_admin_username=docduckgooseacr" -var="acr_admin_password=${{ secrets.ACR_ADMIN_PASSWORD }}"
